#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

        INSERT INTO "public"."ingredients"("name") 
        VALUES('Beans') 
            , ('Baking Powder')
            , ('Bread') 
            , ('Butter') 
            , ('Cheese')
            , ('Chicken stock')
            , ('Chocolate')
            , ('Cinnamon')
            , ('Coconut')
            , ('Cooking apple')
            , ('Condensed milk')
            , ('Gingernut biscuit')
            , ('Plain flour')
            , ('Wholemeal flour')
            , ('Ice-cream')
            , ('Leek')
            , ('Margarine')
            , ('Milk') 
            , ('Nuts'), ('Onion')
            , ('Caster sugar')
            , ('Granulated sugar')
            , ('Icing sugar')
            , ('Olive Oil')
            , ('Vegetable Oil')
            , ('Pepper')
            , ('Potato') 
            , ('Raspberry jelly')
            , ('Salt')
            , ('Tomato')
            , ('Vanilla flavouring') 
        RETURNING "uuid", "name", "created_at", "updated_at";

        INSERT INTO "public"."labels"("name" , "colour")
        VALUES ('lunch', '#FFFF33')
            , ('dessert', '#CA33FF')
            , ('dinner', '#3358FF')
            , ('vegetarian', '#42FF33');

        INSERT INTO "public"."units"("name", "abbreviation")
        VALUES ('centimetre', 'cm')
            , ('cup', 'c')
            , ('grams', 'g')
            , ('fluid ounce', 'fl oz')
            , ('inch', 'in')
            , ('kilogram', 'kg')
            , ('litres', 'l')
            , ('milliliter', 'ml')
            , ('millimetre', 'mm')
            , ('ounce', 'oz')
            , ('pint', 'pt')
            , ('pound', 'lb')
            , ('teaspoon', 'tsp')
            , ('tablespoon', 'tbsp');

        INSERT INTO "public"."recipes"("name", "description", "timing", "serving_size")
        VALUES ('Beans on toast', 'Beans on toast', '5', 2);

        INSERT INTO "public"."steps"("index", "instruction", "recipe_id")
        VALUES (1, 'Open tin and pour contents into saucepan', (SELECT uuid FROM recipes WHERE name='Beans on toast'))
            , (2, 'Put saucepan on hob over a medium heat', (SELECT uuid FROM recipes WHERE name='Beans on toast'))
            , (3, 'Stir while cooking', (SELECT uuid FROM recipes WHERE name='Beans on toast'))
            , (4, 'Make toast using the toaster', (SELECT uuid FROM recipes WHERE name='Beans on toast'))
            , (5, 'Put toast on a plate and pour the beans over the toast', (SELECT uuid FROM recipes WHERE name='Beans on toast'))
            , (6, 'Sprinkle over some cheese', (SELECT uuid FROM recipes WHERE name='Beans on toast')) 
            , (7, 'Steep saucepan in cold water and switch off the cooker', (SELECT uuid FROM recipes WHERE name='Beans on toast'))
            , (8, 'Stack dishes, clean table and wash up.', (SELECT uuid FROM recipes WHERE name='Beans on toast'));

        INSERT INTO "public"."equipment"("name") 
        VALUES ('Baking bowl')
            , ('Mixing bowl')
            , ('Baking paper')
            , ('Baking tray')
            , ('Balloon whisk')
            , ('Blender') 
            , ('Cake tin')
            , ('Chopping board')
            , ('Clingfilm')
            , ('Colander')
            , ('Cooling tray')
            , ('Corer') 
            , ('Glass')
            , ('Fork')
            , ('Food processor') 
            , ('Grater')
            , ('Bread knife') 
            , ('Butter knife')
            , ('Palette knife')
            , ('Vegetable knife') 
            , ('Measuring jug')
            , ('Pastry brush')
            , ('Pastry cutter')
            , ('Peeler') 
            , ('Potato masher')
            , ('Tinfoil')
            , ('Toaster') 
            , ('Sandwich maker') 
            , ('Frying pan')
            , ('Saucepan')
            , ('Sieve')
            , ('Straw')
            , ('Dessert spoon')
            , ('Tablespoon') 
            , ('Teaspoon') 
            , ('Wooden spoon') 
        RETURNING "uuid", "name", "created_at", "updated_at";

EOSQL
