version: '3'

services:

  nginx:
    build: ./docker/nginx
    ports:
    - "8989:80"
    volumes:
    - ./public:/server/http/public
    environment:
      PHP_FPM_URI: php:9000
    links:
    - php

  php:
    build:
      dockerfile: ./docker/php-fpm/Dockerfile
      context: .
      args:
        ENABLE_XDEBUG: "True"
    volumes:
    - ./:/server/http
    env_file:
    - .env
    links:
    - postgres

  postgres:
    build:
      dockerfile: ./docker/postgres/Dockerfile
      context: .
    ports:
    - "5489:5432"
    volumes:
    - ./docker/postgres/volume:/tmp
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: recipes
      POSTGRES_PASSWORD: sepicer
      POSTGRES_DB: recipes
